name: Testmac

# Controls when the action will run. 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: release
        run: |
          more /etc/*release | cat || true
          openssl version || true
          find / -name libcrypto.dylib* -ls
