name: Testmac

# Controls when the action will run. 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: release
        run: |
          lsb_release -a
          openssl version
          find / -name libcrypto.dylib* -ls
