name: Testmac

# Controls when the action will run. 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: release
        run: |
          openssl version || true
          find /usr \( -name libcrypto.dylib -o -name libcrypto.*.dylib \) -ls 2>/dev/null || true
          find /opt \( -name libcrypto.dylib -o -name libcrypto.*.dylib \) -ls 2>/dev/null || true
